services:
  app:
    build:
      context: .
      args:
        SERVER_PORT: ${SERVER_PORT}

    image: oheyek/justlearnitpage-app:latest

    expose:
      - "${SERVER_PORT}"

    volumes:
      - ./db:/app/db

    env_file:
      - .env

    networks:
      - web

    restart: unless-stopped

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  caddy:
    image: caddy:2
    env_file:
      - .env
    container_name: caddy
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    networks:
      - web

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup --label-enable

networks:
  web:

volumes:
  caddy_data:
  caddy_config:
