name: Dockerless CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: codeberg-tiny

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image with Buildah
        run: |
          buildah --storage-driver=vfs bud -t my-app:latest .

      - name: List images
        run: buildah images
