CREATE TABLE posts (
  id INTEGER PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  header TEXT NOT NULL,
  subheader TEXT NOT NULL,
  post_content TEXT NOT NULL,
  sources TEXT NOT NULL,
  is_public INTEGER DEFAULT 1 NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
)
