INSERT INTO
  posts (
    slug,
    header,
    subheader,
    short_description,
    post_content,
    sources
  )
VALUES
  (
    'what-is-jli',
    'What is JLI?',
    'Foundations',
    'An introduction to Just Learn IT and what you can expect from upcoming courses.',
    '
        <div class="post-content">
          <h3 class="post-header" id="introduction">Introduction</h3>
          <p>
            The Just Learn IT project is an open-source solution for providing
            the best educational sources to let you learn what you desire.
          </p>
          <p>
            This post is an introduction to getting to know how the whole
            project and the site work.
          </p>
        </div>
        <div class="post-content">
          <h3 class="post-header" id="overview">How does it work?</h3>
          <p>
            But let''s start from the beginning. How do we want to provide
            educational materials on the site? It''s simple. This site contains a
            course section where you can actually find all the content in the
            form of text posts.
          </p>
          <p>
            For now, posts are in the form of unordered lists. Every post will
            contain fully accessible educational materials in text format,
            available for free.
          </p>
          <p>
            Besides that, at the end of every post there will be more links
            worth checking out if you want to go much deeper into a specific
            topic. Posts will be written clearly so you can understand them
            without having to reread them often. But hey, if you want to go
            deeper into some topic, we will provide that solution too.
          </p>
        </div>
        <div class="post-content">
          <h3 class="post-header" id="future">Future project development</h3>
          <p>
            We know that currently this site does not provide many features.
            We''re trying to improve that and provide you with the best content
            we can. But it requires time.
          </p>
          <p>
            We are committed to ensuring that both the new features on the
            website and the content we publish are of the highest quality, which
            is why we will be rolling them out on an irregular basis. We have
            plenty of ideas, but unfortunately time is limited, and we want to
            do this as well as possible.
          </p>
        </div>
        <div class="post-content">
          <h3 class="post-header" id="simplicity">Simplicity</h3>
          <p>
            The site’s simplicity also stems from our approach to creating
            educational materials.
          </p>
          <p>
            In an age where today’s media influence our ability to focus, we
            opted for the simplest possible design, one that requires a certain
            amount of adjustment on the part of anyone who wants to learn
            something. You won’t find any flashy effects or dopamine-inducing
            elements here, unlike with short-form content.
          </p>
        </div>
        <div class="post-content">
          <h3 class="post-header" id="open-source">Open source</h3>
          <p>
            The entire project website is open source and available on GitHub as
            of the time of writing this post (the link will be provided in the
            sources).
          </p>
          <p>
            We encourage you to contribute your own features to the site if you
            have the necessary expertise and your code was not generated by AI.
          </p>
        </div>
        <div class="post-content">
          <h3 class="post-header" id="summary">Summary</h3>
          <p>
            In summary, we want both ourselves and our readers to give each
            other a chance, while understanding that some things take time to
            refine.
          </p>
          <p>
            We believe that anyone can learn anything, and we want to create a
            platform for that, but it takes time. Let’s trust each other.
          </p>
        </div>
  ',
    '

          <h3 class="post-header" id="sources-heading">Sources</h3>
          <ul>
            <li>
              <a
                href="https://www.theodinproject.com"
                target="_blank"
                rel="noopener noreferrer"
                >The Odin Project</a
              >
              - The main inspiration behind this project
            </li>
            <li>
              <a
                href="https://codeberg.org/JustLearnIT/JustLearnITPage"
                target="_blank"
                rel="noopener noreferrer"
                >Project repository</a
              >
              - The web page for this project (which you are currently viewing)
            </li>
          </ul>
  '
  );
