name: Build Docker Image

on:
  push:
    branches:
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            --build-arg SERVER_PORT=${{ secrets.SERVER_PORT }} \
            -t oheyek/justlearnitpage-app:latest .
