name: Build & Deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --build-arg SERVER_PORT=${{ secrets.SERVER_PORT }} \
            -t ${{ secrets.DOCKER_USERNAME }}/justlearnitpage-app:latest .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/justlearnitpage-app:latest

      - name: SSH Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.PORT}}
          script: |
            cd ~/jli-page
            docker compose pull
            docker compose up -d
